label OpenWrt
  kernel /kernel.img
  fdt /sunxi.dtb
  append root=/dev/mmcblk0p2 console=ttyAS0,115200n8 rootwait clk_ignore_unused mac_addr=${mac} quiet loglevel=8 earlycon console=tty1 coherent_pool=2M kasan=off init=/sbin/init
